name: example
description: Flutter Timeline package demo app

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  timeline_list:
    path: ../

flutter:
  uses-material-design: true
